version: "3"
services:
  server:
    build: ./
    command: sh -c "bundle && rails s"
    ports:
    - 3000:3000
    volumes:
    - bundle:/usr/local/bundle
    - ./:/app
    tmpfs:
    - /app/tmp/pids
  client:
    build: ./client
    command: sh -c "yarn && yarn run start"
    environment:
      PORT: 3001
    ports:
    - 3001:3001
    volumes:
    - node_modules:/app/node_modules
    - ./client:/app
    depends_on:
    - server
volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
