# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0443d676550b1c6ae787eacb87e69808a344fc6fac797d53b6217dc3147679caa0be7a89bd9d3c5c9e090baf0fa02ed2bd2ac439f96d39e10e27c1b2115aa3aa

test:
  secret_key_base: f1d0aeceb8537e229d0e36f20f873875a7bd61082757509b1171853522eec3354c961d1f653c0a86d20600a61737b6f317f5c7e45c70af1e3ed3c2bd274597e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
